version: "3.9"
services:
  app:
    build: .
    container_name: voting-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/voting?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_ISSUER: ${SECURITY_JWT_ISSUER}
      SECURITY_JWT_EXPIRATION_MINUTES: ${SECURITY_JWT_EXPIRATION_MINUTES}
  mysql:
    image: mysql:8.0
    container_name: voting-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting
    ports:
      - "3306:3306"
